### PR TITLE
restart on end of setup or ww engine will not work

### PR DESCRIPTION
**Pull request by AIIX**
- wake word engine never works until the image is manually restarted after setup has completed

### CODE REVIEW

**Comment by JarbasAl** [comment]
why doesnt it work? this PR seems the wrong thing to do, do you have logs about the error so we can fix it in proper place instead of such a drastic ugly hack?

**Comment by AIIX** [comment]
> why doesnt it work? this PR seems the wrong thing to do, do you have logs about the error so we can fix it in proper place instead of such a drastic ugly hack?

There are no error logs except -> https://github.com/OpenVoiceOS/ovos-core/issues/216 but ww engine never responds to wakeword at all until a reboot

**Comment by JarbasAl** [comment]
i really really REALLY dislike this change, if you must do it then:
- maybe use restart instead of reboot, no need to restart full OS
- put it all behind skill settings and disabled by default, this is very platform specific, enable it in images that need it
- perhaps allow settings to define if it wants reboot or a list of services to reboot  (you only need to restart speech for your bug)

in the end this will just hide a bug that needs proper fixing and is unrelated to this skill, it is very hacky and only acceptable as a workaround so you can ship an image

**Comment by AIIX** [comment]
Closing this as this issue is no longer applicable

**Pull request closed without merging**
